[config]
cycles = 1024
algorithm = "NPAG"
tui = false
cache = true

[random]
Ka = [0.001, 3.0]
Ke = [0.001, 3.0]
V = [0.001, 50.0]

[error]
value = 10.0
class = "gamma"
poly = [0.1, 0.1, 0.0, 0.0]

[output]
write = true

[prior]
sampler = "sobol"
points = 100
seed = 347
