[paths]
data = "examples/data/theophylline.csv"
log = "theophylline.log"
#prior = "theta_bimodal_ke.csv"

[config]
cycles = 1024
engine = "NPAG"
init_points = 2129
seed = 347
tui = false
output = true
cache = true
idelta = 0.1
log_level = "info"


[random]
Ke = [0.001, 3.0]
Ka = [0, 3]
V = [0, 250.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]
