[config]
cycles = 100
algorithm = "NPAG"

cache = true

[random]
CLs = [0.0, 2.0]
fm = [0.0, 1.0]
K20 = [0.0, 5.0]
relV = [0.0, 1.0]
theta1 = [-3.0, 1.0]
theta2 = [-3.0, 1.0]
Vs = [0.0, 5.0]

[error]
value = 5
class = "proportional"
poly = [1.0, 0.1, 0.0, 0.0]

[output]
write = true
path = "meta"

[prior]
sampler = "sobol"
points = 2129
seed = 347
