[paths]
data = "examples/simulate/simdata.csv"
prior = "examples/simulate/simprior.csv"
log = "simulate.log"

[config]
cycles = 1024
engine = "NPAG"
init_points = 2129
seed = 22
tui = false
output = true
cache = true
idelta = 0.1
log_level = "info"
sampler = "sobol"
tad = 12.0

[random]
V = [25.0, 250.0]
Ke = [0.001, 3.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]
