[config]
cycles = 1000
algorithm = "NPAG"
cache = true

[random]
ke0 = [0.0001, 2.4]
ske = [0.0001, 0.2]

[error]
value = 1.0
class = "additive"
poly = [-0.00119, 0.44379, -0.45864, 0.16537]

[log]
level = "debug"

[prior]
sampler = "sobol"
points = 1000
seed = 347

[output]
write = true
