[config]
cycles = 1024
algorithm = "NPAG"
tui = false
cache = true

[random]
ke = [0.001, 3.0]
# ske = [0.0, 3.0]
v = [25.0, 250.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]

[log]
level = "info"

[prior]
sampler = "sobol"
points = 2129
seed = 22

[output]
write = true
