[config]
cycles = 100000
algorithm = "NPAG"
tui = false
cache = true

[random]
ske = [0.0, 0.02]
# ke = [0.001, 3.0]
# v = [25.0, 250.0]

[error]
value = 0.01
class = "additive"
poly = [0.0, 0.00, 0.0, 0.0]

[log]
level = "debug"

[prior]
sampler = "sobol"
points = 10
seed =347

[output]
write = true
