[config]
cycles = 100000
algorithm = "NPAG"
tui = false
cache = true

[random]
#_ka, _ke0, _ske, _kcp, _kpc
ka = [0.03, 0.07]
ke0 = [0.03, 0.3]
ske = [0.0, 2.0]
kcp = [0.07, 0.13]
kpc = [0.03, 0.07]


[error]
value = 0.01
class = "additive"
poly = [0.0, 0.00, 0.0, 0.0]

[log]
level = "debug"

[prior]
sampler = "sobol"
points = 10
seed =347

[output]
write = true
