[config]
cycles = 1024
engine = "NPAG"
cache = true

[random]
v1 = [5.0, 160.0]
cl1 = [4.0, 9.0]
v2 = [100.0, 200.0]
cl2 = [25.0, 35.0]
popmax = [100000000.0, 100000000000.0]
kgs = [0.01, 0.25]
kks = [0.01, 0.5]
e50_1s = [0.1, 2.5]
e50_2s = [0.1, 10.0]
alpha_s = [-8.0, 5.0]
kgr1 = [0.004, 0.1]
kkr1 = [0.08, 0.4]
e50_1r1 = [8.0, 17.0]
alpha_r1 = [-8.0, 5.0]
kgr2 = [0.004, 0.3]
kkr2 = [0.1, 0.5]
e50_2r2 = [5.0, 8.0]
alpha_r2 = [-5.0, 5.0]
init_3 = [0.0, 0.0]
init_4 = [-1.0, 4.0]
init_5 = [-1.0, 3.0]
h1s = [0.5, 8.0]
h2s = [0.1, 4.0]
h1r1 = [5.0, 25.0]
h2r2 = [10.0, 22.0]

[error]
value = 1.0
class = "proportional"
poly = [0.1, 0.1, 0.0, 0.0]

[log]
level = "info"

[prior]
sampler = "sobol"
points = 2129
seed = 347

[output]
write = true
path = "examples/drusano/output"

init_points = 2129
seed = 347

