[paths]
data = "examples/data/two_eq_lag.csv"
log_out = "two_eq_lag.log"
#prior_dist = "theta_two_eq_lag.csv"

[config]
cycles = 1000
engine = "NPOD"
init_points = 1000
seed = 22
tui = true
pmetrics_outputs = true
cache = true

[random]
ka = [0.1, 0.9]
ke = [0.001, 0.1]
lag = [0.0, 4.0]
v = [30.0, 120.0]


[error]
value = 0.0
class = "additive"
poly = [0.1, 0.25, -0.001, 0.0]