[paths]
data = "examples/data/two_eq_lag.csv"
log_out = "log/two_eq_lag.log"
#prior_dist = "theta_two_eq_lag.csv"

[config]
cycles = 1000
engine = "NPAG"
init_points = 10000
seed = 347
tui = false
pmetrics_outputs = true

[parameters]
Ka = [0.1, 1.5]
Ke = [0.001, 0.1]
V_max = [30.0, 120.0]
lag = [0.0, 4.0]
