[paths]
data = "examples/data/bimodal_ke.csv"
log_out = "log/bimodal_ke.log"
#prior_dist = "theta_bimodal_ke.csv"

[config]
cycles = 1024
engine = "NPAG"
init_points = 2129
seed = 347
tui = false
pmetrics_outputs = true
cache = true

[random]
Ke = [0.001, 3.0]
V = [25.0, 250.0]

[error]
value = 0.0
class = "additive"
