[config]
cycles = 1024
algorithm = "NPAG"
tui = false
cache = true

[random]
V = [25.0, 250.0]
Ke = [0.001, 3.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]

[log]
level = "info"

[prior]
sampler = "sobol"

[output]
write = true