[paths]
data = "examples/data/bimodal_ke.csv"
log_out = "log/bimodal_ke.log"
#prior_dist = "theta_bimodal_ke.csv"

[config]
cycles = 1024
engine = "NPOD"
init_points = 2129
seed = 347
tui = true
pmetrics_outputs = true
cache = true
idelta = 0.1
log_level = "info"

[random]
Ke = [0.001, 3.0]
V = [25.0, 250.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]
