[paths]
data = "examples/data/bimodal_ke.csv"
log = "log/bimodal_ke.log"
#prior_dist = "theta_bimodal_ke.csv"

[config]
cycles = 1024
engine = "NPAG"
init_points = 2129
tui = true
output = true
cache = true
log_level = "info"

[random]
Ke = [0.001, 3.0]
V = [25.0, 250.0]

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]
