# Currently not in use - settings are defined in main.rs

[config]
cycles = 1024
algorithm = "NPAG"
cache = true

[error]
value = 0.0
class = "additive"
poly = [0.0, 0.05, 0.0, 0.0]

[log]
level = "info"

[prior]
sampler = "sobol"
# file = "examples/bimodal_ke/prior.csv"

[output]
write = true
path = "examples/bimodal_ke/output"
