name: Benchmark PMcore

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  pull-requests: write
  issues: write

jobs:
  benchmark:
    name: Run Rust benchmark PMcore
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Rust
        run: rustup update

      - name: Run benchmark
        run: cargo bench | tee output.txt

      - name: Post benchmark results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: 'Rust Benchmark'
          tool: 'cargo'
          output-file-path: output.txt
          github-token: ${{ secrets.GITHUB_TOKEN }}
          # Always post the benchmark result as a comment
          comment-always: true
          # Alert on performance regression beyond threshold
          alert-threshold: '110%'
          comment-on-alert: true
          fail-on-alert: true
