name: Security Audit

"on":
  push:
    paths:
      - "Cargo.toml"
      - ".github/workflows/security_audit.yml"
  pull_request:
    paths:
      - "Cargo.toml"
  workflow_dispatch:
  schedule:
    - cron: "0 6 1,15 * *"

permissions:
  contents: read
  issues: write
  checks: write

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
      - name: Generate Cargo.lock
        run: cargo generate-lockfile
      - name: Security audit
        uses: rustsec/audit-check@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
